version: "3.9"
services:
  nginx:
    image: nginx:1.23.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - goapi
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: goapi
    # ports:
      # - "5432:5432"
  goapi:
    build: .
    command: ./main
    expose:
    - "3000"
    depends_on:
      - postgres
  