version: "3.9"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goapi
    expose:
    - "5432"
  api:
    build: .
    command: ./main
    environment:
      - PORT=:3000
      - CONSTRING=postgresql://postgres:password@postgres:5432/goapi?sslmode=disable
    expose:
    - "3000"
    depends_on:
      - postgres
    deploy:
      replicas: 2
  nginx:
    image: nginx:1.23.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
  