version: "3.9"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      PGUSER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB_NAME}
    expose:
    - ${PG_PORT}
  api:
    build: .
    command: ./main
    environment:
      - HTTP_PORT=:${API_PORT}
      - DB_USER=${PG_USER}
      - DB_PASS=${PG_PASS}
      - DB_PORT=${PG_PORT}
      - DB_NAME=${PG_DB_NAME}
    expose:
    - ${API_PORT}
    depends_on:
      - postgres
    deploy:
      replicas: 2
  nginx:
    image: nginx:1.23.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
  